### PR TITLE
Setup.sh && Python Package Fix.

### PR DESCRIPTION
**Pull request by ghost**
I had to fix a couple of things for WikiLeaker.py to run.

I added "requests" to the requirements.txt file.

I changed "pip install -U --user -r requirements.txt"

to

"pip install -r requirements.txt" on the setup.sh file.

Also, the packages (python3 python3-pip python3-lxml git libre-dev) don't install on setup.sh because of permission issues.

I added a sudo before "apt install."

### CODE REVIEW

**Comment by ghost** [comment]
I also updated the README.md

**Review by jocephus — APPROVED** [review]

**Review by jocephus — APPROVED** [review]

**Review by jocephus — APPROVED** [review]

**Review by jocephus — APPROVED** [review]

**Review by jocephus — COMMENTED** [review]
Incorrect syntax as this section is referencing the Recon-ng module

**Review by jocephus — APPROVED** [review]

**Comment by ghost** [comment]
Hmmm.... I thought you said in the README.md we could install the standalone version? That is what I am referring to. I haven't tried this out with the Recon-ng module. Still learning about all the OSINT tools out there.

**Comment by ghost** [comment]
Also, I'm pretty new to Github. What does "Changes approved" mean?

**Pull request merged**
